name: Terraform and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_CERT_ARN: ${{ secrets.TF_VAR_CERT_ARN }}
      TF_VAR_ACCESS_KEY: ${{ secrets.TF_VAR_ACCESS_KEY }}
      TF_VAR_SECRET_KEY: ${{ secrets.TF_VAR_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.18.0"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: ./build

  deploy:
    needs: [terraform, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
          path: ./build
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.TF_VAR_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.TF_VAR_SECRET_KEY }}
          aws_bucket: "www.${{ vars.TF_VAR_BUCKET_NAME }}"
          source_dir: "build"
